AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub Actions OIDC Provider and IAM Role for Terraform Operations'

Parameters:
  Repo:
    Description: 'The GitHub organization/repository (format: org/repo)'
    Type: String
    AllowedPattern: '^[a-zA-Z0-9-_]+/[a-zA-Z0-9-_]+$'
    ConstraintDescription: 'Must be in format: organization/repository'
  Environment:
    Description: 'The GitHub Actions environment name'
    Type: String
    Default: 'production'
    AllowedPattern: '^[a-zA-Z0-9-_]+$'
    ConstraintDescription: 'Environment name can only contain alphanumeric characters, hyphens, and underscores'
  TerraformBackendStackName:
    Description: 'Name of the CloudFormation stack that created the S3 backend'
    Type: String
    Default: 'terraform-backend'
  StateBucketName:
    Description: 'Name of the S3 bucket for Terraform state'
    Type: String
    Default: 'gamepulse-tf-backend-resources'

Resources:
  GitHubOIDCProvider:
    Type: 'AWS::IAM::OIDCProvider'
    Properties:
      Url: 'https://token.actions.githubusercontent.com'
      ClientIdList:
        - 'sts.amazonaws.com'
      ThumbprintList:
        - '6938fd4d98bab03faadb97b34396831e3780aea1'
        - '1c58a3a8518e8759bf075b76b750d4f2df264fcd'
      Tags:
        - Key: Purpose
          Value: GitHubActions

  TerraformDeployRole:
    Type: 'AWS::IAM::Role'
    DependsOn: GitHubOIDCProvider
    Properties:
      RoleName: !Sub 'github-actions-${AWS::StackName}'
      Description: 'IAM Role for GitHub Actions to deploy infrastructure using Terraform'
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt GitHubOIDCProvider.Arn
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${Repo}:*'

  TerraformStatePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: 'Policy for accessing Terraform state in S3'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:ListBucket'
              - 's3:GetBucketVersioning'
              - 's3:GetBucketLocation'
            Resource: 
              - !Sub 'arn:aws:s3:::${StateBucketName}'
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
            Resource:
              - !Sub 'arn:aws:s3:::${StateBucketName}/*'
              - !Sub 'arn:aws:s3:::${StateBucketName}/terraform.tfstate'
              - !Sub 'arn:aws:s3:::${StateBucketName}/terraform.tfstate.tflock'
      Roles:
        - !Ref TerraformDeployRole

  TerraformDeployPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: 'Policy for Terraform deployments via GitHub Actions'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              # EC2 Permissions
              - 'ec2:*'
              # VPC Permissions
              - 'vpc:*'
              # IAM Permissions
              - 'iam:GetRole'
              - 'iam:CreateRole'
              - 'iam:DeleteRole'
              - 'iam:PutRolePolicy'
              - 'iam:GetRolePolicy'
              - 'iam:DeleteRolePolicy'
              - 'iam:ListRolePolicies'
              - 'iam:ListAttachedRolePolicies'
              - 'iam:AttachRolePolicy'
              - 'iam:DetachRolePolicy'
              - 'iam:PassRole'
              # CloudWatch Logs
              - 'logs:*'
              # KMS for Encryption
              - 'kms:*'
            Resource: '*'
      Roles:
        - !Ref TerraformDeployRole

Outputs:
  RoleARN:
    Description: 'ARN of the IAM Role for GitHub Actions'
    Value: !GetAtt TerraformDeployRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleARN'
  
  RoleName:
    Description: 'Name of the IAM Role for GitHub Actions'
    Value: !Ref TerraformDeployRole
    Export:
      Name: !Sub '${AWS::StackName}-RoleName'

  OIDCProviderArn:
    Description: 'ARN of the OIDC Provider'
    Value: !GetAtt GitHubOIDCProvider.Arn
    Export:
      Name: !Sub '${AWS::StackName}-OIDCProviderArn' 