AWSTemplateFormatVersion: 2010-09-09
Description: GitHub OIDC Role for GamePulse Terraform Deployment and Lambda Container Deployments

Resources:
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHub_Actions_Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                'token.actions.githubusercontent.com:sub': 'repo:Ajay263/Gaming-Analytics-DataLakehouse:*'
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
      Policies:
        - PolicyName: GitHubActionsDeployPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # S3 Permissions
              - Sid: S3Access
                Effect: Allow
                Action: 
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource: 
                  - arn:aws:s3:::gaming-analytics-*
                  - arn:aws:s3:::gaming-analytics-*/*
                  
              # IAM Permissions for Lambda Role Management
              - Sid: IAMAccess
                Effect: Allow
                Action: 
                  - iam:GetRole
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PassRole
                Resource: 
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/gaming-analytics-*
                  
              # Lambda Permissions
              - Sid: LambdaAccess
                Effect: Allow
                Action: 
                  - lambda:CreateFunction
                  - lambda:DeleteFunction
                  - lambda:GetFunction
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - lambda:AddPermission
                  - lambda:RemovePermission
                  - lambda:ListVersionsByFunction
                  - lambda:PublishVersion
                  - lambda:CreateAlias
                  - lambda:DeleteAlias
                  - lambda:UpdateAlias
                Resource: !Sub arn:aws:lambda:*:${AWS::AccountId}:function:gaming-analytics-*
                  
              # ECR Permissions for Container Deployments
              - Sid: ECRAccess
                Effect: Allow
                Action: 
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:GetRepositoryPolicy
                  - ecr:DescribeRepositories
                  - ecr:ListImages
                  - ecr:DescribeImages
                  - ecr:BatchGetImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                Resource: !Sub arn:aws:ecr:*:${AWS::AccountId}:repository/gaming-analytics-*
                  
              # CloudWatch Permissions for Lambda Logs
              - Sid: CloudWatchAccess
                Effect: Allow
                Action: 
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: 
                  - !Sub arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/lambda/gaming-analytics-*
                  - !Sub arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/lambda/gaming-analytics-*:*
                  
              # EventBridge Permissions for Lambda Triggers
              - Sid: EventBridgeAccess
                Effect: Allow
                Action: 
                  - events:PutRule
                  - events:DeleteRule
                  - events:PutTargets
                  - events:RemoveTargets
                  - events:DescribeRule
                Resource: !Sub arn:aws:events:*:${AWS::AccountId}:rule/gaming-analytics-*
                  
              # Global Read Permissions
              - Sid: GlobalReadPermissions
                Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                  - iam:GetAccountSummary
                  - ecr:GetAuthorizationToken
                Resource: "*"

  GitHubActionsOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
      Url: https://token.actions.githubusercontent.com